name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17.5-alpine
        env:
          POSTGRES_USER: gmfam
          POSTGRES_PASSWORD: gmfam123
          POSTGRES_DB: gmfam_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Wait for PostgreSQL
      run: |
        until pg_isready -h 127.0.0.1 -p 5432 -U gmfam; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        echo "PostgreSQL is ready!"

    - name: Test
      env:
        PAGODA_APP_ENVIRONMENT: test
        PAGODA_DATABASE_DRIVER: postgres
        PAGODA_DATABASE_TESTCONNECTION: "postgres://gmfam:gmfam123@127.0.0.1:5432/gmfam_test?sslmode=disable"
      run: make test
