name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.24

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Verify environment
      env:
        SKIP_DB_TESTS: "true"
      run: |
        echo "SKIP_DB_TESTS is set to: $SKIP_DB_TESTS"
        echo "Environment variables:"
        env | grep SKIP || echo "SKIP_DB_TESTS not found"

    - name: Test
      env:
        SKIP_DB_TESTS: "true"
      run: make test
